// This code was autogenerated with `dbus-codegen-rust -s -m None -o rs_wl_gammarelay.rs --file wl-gammarelay.xml`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>>
    OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C>
{
    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusPeer
    for blocking::Proxy<'a, C>
{
    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait RsWlGammarelay {
    fn update_temperature(&self, delta_temp: i16) -> Result<(), dbus::Error>;
    fn update_gamma(&self, delta_gamma: f64) -> Result<(), dbus::Error>;
    fn update_brightness(&self, delta_brightness: f64) -> Result<(), dbus::Error>;
    fn toggle_inverted(&self) -> Result<(), dbus::Error>;
    fn brightness(&self) -> Result<f64, dbus::Error>;
    fn set_brightness(&self, value: f64) -> Result<(), dbus::Error>;
    fn gamma(&self) -> Result<f64, dbus::Error>;
    fn set_gamma(&self, value: f64) -> Result<(), dbus::Error>;
    fn inverted(&self) -> Result<bool, dbus::Error>;
    fn set_inverted(&self, value: bool) -> Result<(), dbus::Error>;
    fn temperature(&self) -> Result<u16, dbus::Error>;
    fn set_temperature(&self, value: u16) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> RsWlGammarelay
    for blocking::Proxy<'a, C>
{
    fn update_temperature(&self, delta_temp: i16) -> Result<(), dbus::Error> {
        self.method_call("rs.wl.gammarelay", "UpdateTemperature", (delta_temp,))
    }

    fn update_gamma(&self, delta_gamma: f64) -> Result<(), dbus::Error> {
        self.method_call("rs.wl.gammarelay", "UpdateGamma", (delta_gamma,))
    }

    fn update_brightness(&self, delta_brightness: f64) -> Result<(), dbus::Error> {
        self.method_call("rs.wl.gammarelay", "UpdateBrightness", (delta_brightness,))
    }

    fn toggle_inverted(&self) -> Result<(), dbus::Error> {
        self.method_call("rs.wl.gammarelay", "ToggleInverted", ())
    }

    fn brightness(&self) -> Result<f64, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "rs.wl.gammarelay",
            "Brightness",
        )
    }

    fn gamma(&self) -> Result<f64, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "rs.wl.gammarelay",
            "Gamma",
        )
    }

    fn inverted(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "rs.wl.gammarelay",
            "Inverted",
        )
    }

    fn temperature(&self) -> Result<u16, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "rs.wl.gammarelay",
            "Temperature",
        )
    }

    fn set_brightness(&self, value: f64) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(
            self,
            "rs.wl.gammarelay",
            "Brightness",
            value,
        )
    }

    fn set_gamma(&self, value: f64) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(
            self,
            "rs.wl.gammarelay",
            "Gamma",
            value,
        )
    }

    fn set_inverted(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(
            self,
            "rs.wl.gammarelay",
            "Inverted",
            value,
        )
    }

    fn set_temperature(&self, value: u16) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(
            self,
            "rs.wl.gammarelay",
            "Temperature",
            value,
        )
    }
}

pub trait OrgFreedesktopDBusProperties {
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusProperties
    for blocking::Proxy<'a, C>
{
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Get",
            (interface_name, property_name),
        )
        .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>,)| Ok(r.0))
    }

    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Set",
            (interface_name, property_name, value),
        )
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "GetAll",
            (interface_name,),
        )
        .and_then(|r: (arg::PropMap,)| Ok(r.0))
    }
}
